/** @format */

export class Places {
  constructor(title, imgurl, location, id) {
    (this.id = id),
      (this.title = title),
      (this.imgurl = imgurl),
      (this.address = location.address),
      (this.location = { lat: location.lat, lng: location.lng });
  }
}

//After installe SQLite database ,  deleted manual id , and put id parameter into constuctor ,
//that id will be auto generated by sqlite databse in database file, with insertplace function
